const estilos = {
  container: {
    padding: "40px 20px",
    fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    backgroundColor: "#f4f4f4",
    minHeight: "100vh",
    color: "#1a1a1a",
  },
  card: {
    maxWidth: "680px",
    margin: "0 auto",
    backgroundColor: "white",
    padding: "40px",
    borderRadius: "12px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.05)",
  },
  logoSpace: {
    textAlign: "center",
    marginBottom: "30px",
    borderBottom: "1px solid #eee",
    paddingBottom: "20px",
  },
  h1: {
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: "2px",
    fontWeight: "300",
    fontSize: "24px",
    color: "#000",
    margin: "0 0 10px 0",
  },
  p: {
    textAlign: "center",
    color: "#888",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "1px",
    margin: "0",
  },
  panelGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
    marginBottom: "20px",
  },
  panelItem: {
    backgroundColor: "#fff",
    border: "1px solid #eee",
    padding: "15px",
    borderRadius: "8px",
    textAlign: "center",
  },
  panelMonto: {
    fontWeight: "700",
    fontSize: "18px",
    color: "#000",
  },
  panelLabel: {
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "1px",
    color: "#888",
    display: "block",
    marginBottom: "5px",
  },
  section: {
    borderBottom: "1px solid #eee",
    paddingBottom: "15px",
    marginBottom: "15px",
  },
  labelCheck: {
    fontWeight: "500",
    fontSize: "14px",
    color: "#333",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  input: {
    padding: "10px",
    borderRadius: "4px",
    border: "1px solid #ddd",
    fontSize: "14px",
    width: "90%",
    outline: "none",
  },
  inputNumber: {
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #eee",
    fontSize: "13px",
    width: "60px",
    textAlign: "center",
  },
  btnAdd: {
    fontSize: "11px",
    background: "none",
    border: "1px solid #999",
    color: "#666",
    padding: "5px 10px",
    borderRadius: "4px",
    cursor: "pointer",
    textTransform: "uppercase",
    marginTop: "5px",
  },
  btnSubmit: {
    width: "100%",
    padding: "20px",
    background: "#000",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "2px",
    cursor: "pointer",
    transition: "background 0.3s",
  },
  photoContainer: {
    marginTop: "10px",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },
  photoThumb: {
    width: "80px",
    height: "80px",
    objectFit: "cover",
    borderRadius: "4px",
    border: "1px solid #ddd",
  },
};

export default estilos;